project_id = "shuhmvmdkjspgawygqyf"

[functions]
  [functions.asr]
    verify_jwt = false
  [functions.asrphone]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.jyutping]
    verify_jwt = false
  [functions.voice-clone]
    verify_jwt = false
  [functions.openrouter-insight]
    verify_jwt = false
